/**
 * Turns the guides in `content/` into three build products:
 *
 *   src/generated/guides.js   the docs page's rendered HTML + sidebar TOC
 *   public/llms.txt           the llms.txt index, for agents that want a map
 *   public/llms-full.txt      every guide concatenated, for agents that want
 *                             the whole thing in one fetch
 *
 * The markdown files are the single source of truth: the same bytes are
 * committed as WIKI.md in nexus-energy and nexus-opt (see scripts/sync-guides.mjs),
 * so the website and the repositories cannot drift apart.
 *
 * Run automatically by `npm run build`; run on its own with `npm run docs`.
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { marked } from "marked";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const SITE = "https://vishalram24.github.io/nexus";

/** The guides, in the order they should appear. */
const GUIDES = [
  {
    slug: "energy",
    file: "nexus-energy.md",
    pkg: "nexus-energy",
    repo: "https://github.com/VishalRam24/nexus-energy",
    pypi: "https://pypi.org/project/nexus-energy/",
    blurb:
      "Energy-system optimisation: capacity expansion, dispatch, unit commitment, " +
      "power flow — plus differentiable inverse calibration that recovers the " +
      "hidden inputs behind an observed dispatch.",
  },
  {
    slug: "opt",
    file: "nexus-opt.md",
    pkg: "nexus-opt",
    repo: "https://github.com/VishalRam24/nexus-opt",
    pypi: "https://pypi.org/project/nexus-opt/",
    blurb:
      "The Rust-core solver underneath: LP, MILP, QP, conic, nonlinear, " +
      "black-box, multi-objective and stochastic programming behind one API.",
  },
];

/**
 * GitHub's heading-anchor rule, so the in-content `[…](#3-your-first-model)`
 * links written in the markdown resolve identically on the site and on GitHub.
 */
function slugify(text) {
  return text
    .toLowerCase()
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-");
}

/** Strip inline markdown so a heading reads cleanly in the sidebar. */
function plain(text) {
  return text
    .replace(/`([^`]*)`/g, "$1")
    .replace(/\*\*([^*]*)\*\*/g, "$1")
    .replace(/\*([^*]*)\*/g, "$1")
    .replace(/\[([^\]]*)\]\([^)]*\)/g, "$1");
}

/**
 * Pull the h2/h3 outline straight from the markdown rather than from the
 * rendered HTML — fenced code blocks can contain `#` lines, and those are not
 * headings.
 */
function outline(md) {
  const items = [];
  let inFence = false;
  for (const line of md.split("\n")) {
    if (/^```/.test(line)) { inFence = !inFence; continue; }
    if (inFence) continue;
    const m = /^(#{2,3})\s+(.*)$/.exec(line);
    if (!m) continue;
    const text = plain(m[2].trim());
    items.push({ level: m[1].length, text, id: slugify(text) });
  }
  return items;
}

/** Inject the anchor ids marked does not add, and make wide blocks scrollable. */
function decorate(html) {
  return html
    .replace(/<(h[23])>(.*?)<\/\1>/gs, (_, tag, inner) => {
      const id = slugify(plain(inner.replace(/<[^>]+>/g, "")));
      return `<${tag} id="${id}"><a class="anchor" href="#${id}" aria-label="Link to this section">#</a>${inner}</${tag}>`;
    })
    .replace(/<table>/g, '<div class="table-wrap"><table>')
    .replace(/<\/table>/g, "</table></div>")
    .replace(/<pre>/g, '<div class="code-wrap"><pre>')
    .replace(/<\/pre>/g, "</pre></div>")
    // A blockquote carrying the ⚠ marker is a caveat, and caveats are the one
    // thing the palette reserves `ember` for.
    .replace(/<blockquote>([\s\S]*?)<\/blockquote>/g, (m, inner) =>
      inner.includes("⚠")
        ? `<blockquote class="warn">${inner}</blockquote>`
        : m,
    );
}

/**
 * The guides carry a `## Contents` list because GitHub renders markdown with no
 * navigation of its own. The website has a sidebar, so that list is dropped
 * from the HTML — and from the outline, which is what feeds the sidebar.
 */
function dropContents(md) {
  return md.replace(/\n## Contents\n[\s\S]*?\n---\n/, "\n");
}

const built = [];
for (const g of GUIDES) {
  const md = readFileSync(join(root, "content", g.file), "utf8");
  const web = dropContents(md);
  const title = (/^#\s+(.*)$/m.exec(md) || [, g.pkg])[1];
  built.push({
    ...g,
    title,
    md,
    html: decorate(marked.parse(web, { mangle: false, headerIds: false })),
    toc: outline(web),
  });
}

// ---- src/generated/guides.js ------------------------------------------------
mkdirSync(join(root, "src", "generated"), { recursive: true });
writeFileSync(
  join(root, "src", "generated", "guides.js"),
  "// GENERATED by scripts/build-docs.mjs from content/*.md — do not edit.\n" +
    "export const GUIDES = " +
    JSON.stringify(
      built.map(({ slug, pkg, title, repo, pypi, blurb, html, toc }) => ({
        slug, pkg, title, repo, pypi, blurb, html, toc,
      })),
      null,
      2,
    ) +
    ";\n",
);

// ---- public/llms.txt --------------------------------------------------------
// `public/` holds nothing but these two generated files, so git does not track
// the directory and a fresh clone does not have it.
mkdirSync(join(root, "public"), { recursive: true });
// Follows the llms.txt convention: an H1, a blockquote summary, then linked
// sections an agent can fetch selectively.
const llms = `# Nexus

> Differentiable energy-system optimisation for Python. Nexus solves capacity
> expansion, economic dispatch, unit commitment and optimal power flow at exact
> parity with PyPSA and GenX, and additionally differentiates through the
> optimisation to recover the techno-economic inputs behind an observed
> dispatch — answering "which of my inputs is wrong?" in a handful of solves
> instead of a sampling campaign.

Two packages. \`nexus-energy\` is the energy-system modelling layer and is what
most users want; it installs \`nexus-opt\`, the Rust solver core, automatically.

\`\`\`bash
pip install nexus-energy
\`\`\`

Every code example in the guides below has been executed against a clean
install; printed outputs are real. Where the library's scope stops, the guides
say so explicitly rather than omitting it.

## Guides

${built
  .map(
    (g) =>
      `- [${g.pkg} user guide](${g.repo.replace("github.com", "raw.githubusercontent.com")}/main/WIKI.md): ` +
      `${g.blurb.replace(/\s+/g, " ")} Markdown. Rendered at ${SITE}/docs/?p=${g.slug}`,
  )
  .join("\n")}
- [Everything in one file](${SITE}/llms-full.txt): both guides concatenated as markdown — the complete documentation in a single fetch.

## Source

${built
  .map(
    (g) =>
      `- [${g.pkg}](${g.repo}): source, tests and benchmarks. Released on PyPI as \`${g.pkg}\` (${g.pypi}).`,
  )
  .join("\n")}
- [Project site](${SITE}/): overview, and an explicit statement of what the library does not claim.

## Optional

- [Benchmark scorecard](https://github.com/VishalRam24/nexus-energy/blob/main/COMPARISON_SCORECARD.md): every measured head-to-head, including the one open case where nexus under-counts OPEX by ~4.3% and reports it as a bug rather than a win.
- [Feature matrix](https://github.com/VishalRam24/nexus-energy/blob/main/FEATURE_MATRIX.md): parity table against PyPSA, GenX, Calliope, oemof, SpineOpt, Sienna, PowerModels and Tulipa.
`;
writeFileSync(join(root, "public", "llms.txt"), llms);

// ---- public/llms-full.txt ---------------------------------------------------
const full =
  `# Nexus — complete documentation\n\n` +
  `> Generated from the same markdown that is published as WIKI.md in each\n` +
  `> repository and rendered at ${SITE}/docs/. Every code example here has been\n` +
  `> executed against a clean install.\n\n` +
  `Install: \`pip install nexus-energy\` (pulls in nexus-opt automatically).\n\n` +
  `---\n\n` +
  built.map((g) => g.md.trim()).join("\n\n---\n\n") +
  "\n";
writeFileSync(join(root, "public", "llms-full.txt"), full);

const kb = (s) => `${(Buffer.byteLength(s) / 1024).toFixed(1)} kB`;
console.log(
  `docs: ${built.map((g) => `${g.pkg} (${g.toc.length} headings)`).join(", ")}\n` +
    `      llms.txt ${kb(llms)} · llms-full.txt ${kb(full)}`,
);
